name: Run Python Script on PR Merge

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tabulate termcolor

    - name: Run Python script
      run: python runner.py

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update README.md via Python script"
        git push origin HEAD:${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
